---
- hosts: localhost
  remote_user: ubuntu
  become: yes
  gather_facts: no
  
  pre_tasks:  #install all of this on the new vault server:

    - name: Update repositories cache
      become: yes
      apt:
        update_cache: yes    

    - name: 'install curl'
      retries: 5
      become: yes
      shell: 'apt-get -y install curl'

    - name: mkdir for the vault files
      shell: mkdir -p /home/ubuntu/vault

    - name: get the hashicorp cert
      shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

    - name: add hashicorp repo to local repo
      shell: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

    - name: install vault
      shell: sudo apt-get update && sudo apt-get install vault

    - name: copy vault to /usr/local/bin
      shell: cp vault /usr/local/bin

    - name: chmod
      shell: chmod 755 /usr/local/bin/vault

###---
